### ISSUE TITLE
Test v4.0 with WP 4.9.x

### ISSUE THREAD

**Issue by aristath** [themeum/kirki#2188]
v4.0 requires WP 5.0+ because we're using the `wp-hooks` script, mostly for `postMessage` changes in complex fields like `typography` etc, but also to init these complex fields.

As a fallback I added that script in the `compatibility` package and it will be enqueued in case the user in on an older WordPress version.
We need to test that implementation and make sure it works.

**Comment by ArekZw** [comment]
Test on Wordpress 4.9.4:

```
2019/08/19 23:48:42 [error] 2273#2273: *174 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Class 'Kirki\Compatibility\URL' not found in /var/www/html/wordpress4/wp-content/plugins/kirki/packages/kirki-framework/compatibility/src/Scripts.php:50
Stack trace:
#0 /var/www/html/wordpress4/wp-includes/class-wp-hook.php(286): Kirki\Compatibility\Scripts->register_scripts('')
#1 /var/www/html/wordpress4/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#2 /var/www/html/wordpress4/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#3 /var/www/html/wordpress4/wp-includes/script-loader.php(1435): do_action('wp_enqueue_scri...')
#4 /var/www/html/wordpress4/wp-includes/class-wp-hook.php(286): wp_enqueue_scripts('')
#5 /var/www/html/wordpress4/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#6 /var/www/html/wordpress4/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#7 /var/www/html/wordpress4/wp-includes/general-template.php(2614): do_action('wp_head')
#8 /var/www/html/wordpress4/wp-content/themes/astra/he" while reading response header from upstream, client: 127.0.0.1, server: 127.0.0.1, request: "GET /wordpress4/test-15/ HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.2-fpm.sock:", host: "127.0.0.1", referrer: "http://127.0.0.1/wordpress4/wp-admin/post.php?post=3128&action=edit&lang=pl"
```
